export default {
  type: "ingredients-data",
  data: [
    {
      id: 13,
      name: "Cutlet",
      src: "/items/cutlet.svg",
      displaysrc: "/renderItems/cutlet.svg",
      price: 1,
      time: 1,
      weight: 5,
      energy: 20,
      count: 0,
    },
    {
      id: 14,
      name: "Mayo",
      src: "/items/mayo.svg",
      displaysrc: "/renderItems/mayo.svg",
      price: 2,
      time: 1,
      weight: 3,
      energy: 5,
      count: 0,
    },
    {
      id: 15,
      name: "Onion",
      src: "/items/onion.svg",
      displaysrc: "/renderItems/onion.svg",
      price: 1,
      time: 1,
      weight: 2,
      energy: 4,
      count: 0,
    },
    {
      id: 16,
      name: "Tomatoe",
      src: "/items/tomatoe.svg",
      displaysrc: "/renderItems/tomatoe.svg",
      price: 1,
      time: 1,
      weight: 2,
      energy: 10,
      count: 0,
    },
    {
      id: 17,
      name: "Cucumber",
      src: "/items/cucumber.svg",
      displaysrc: "/renderItems/cucumber.svg",
      price: 1,
      time: 1,
      weight: 4,
      energy: 7,
      count: 0,
    },
    {
      id: 18,
      name: "Cheese",
      src: "/items/cheese.svg",
      displaysrc: "/renderItems/cheese.svg",
      price: 2,
      time: 1,
      weight: 5,
      energy: 15,
      count: 0,
    },
    {
      id: 19,
      name: "Salad",
      src: "/items/salad.svg",
      displaysrc: "/renderItems/salad.svg",
      price: 1,
      time: 1,
      weight: 2,
      energy: 12,
      count: 0,
    },
    {
      id: 20,
      name: "Bun",
      src: "/renderItems/bun_top.svg",
      displaysrc: "/renderItems/bun_top.svg",
      price: 1,
      time: 1,
      weight: 3,
      energy: 1,
      count: 0,
    },
  ],
};
